include: package:very_good_analysis/analysis_options.yaml
linter:
# rules:
#   avoid_classes_with_only_static_members: false
#   sort_constructors_first: true
#   prefer_single_quotes: true

analyzer:
  errors:
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
