name: pumpkin
description: "pumpkin"
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  auto_route: ^9.2.2
  get_it: ^7.7.0
  either_dart: ^1.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  # Пакет с нашими кастомными виджетами.
  ui_kit:
    path: ui_kit
  flutter_bloc: ^8.1.6
  extended_image: ^9.0.6
  hexcolor: ^3.0.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  very_good_analysis: ^6.0.0



flutter:
  generate: true
  uses-material-design: true

  # -- Assets --
  assets:
    - assets/
    - assets/images/
    - assets/json/
